name: ci

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract platform info
        id: platform
        run: echo "arch=$(echo ${{ matrix.platform }} | cut -d'/' -f2)" >> $GITHUB_OUTPUT
      - name: Build container image
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: ${{ matrix.platform }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/game-server-node:buildcache-${{ steps.platform.outputs.arch }}
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/game-server-node:buildcache-${{ steps.platform.outputs.arch }},mode=max
          tags: |
            ghcr.io/${{ github.repository_owner }}/game-server-node:${{ github.sha }}-${{ steps.platform.outputs.arch }}
            ghcr.io/${{ github.repository_owner }}/game-server-node:latest-${{ steps.platform.outputs.arch }}
  merge:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create manifest list and push
        run: |
          docker buildx imagetools create -t ghcr.io/${{ github.repository_owner }}/game-server-node:latest \
            ghcr.io/${{ github.repository_owner }}/game-server-node:latest-amd64 \
            ghcr.io/${{ github.repository_owner }}/game-server-node:latest-arm64
          docker buildx imagetools create -t ghcr.io/${{ github.repository_owner }}/game-server-node:${{ github.sha }} \
            ghcr.io/${{ github.repository_owner }}/game-server-node:${{ github.sha }}-amd64 \
            ghcr.io/${{ github.repository_owner }}/game-server-node:${{ github.sha }}-arm64
      # - name: Delete Package Versions
      #   uses: actions/delete-package-versions@v5.0.0
      #   with:
      #     package-name: game-server-node
      #     package-type: container
      #     # We need at least 8 saved images to support multi-architecture builds and caching:
      #     # - 1 multi-arch manifest list (e.g., 'latest') that references platform-specific images
      #     # - 2 platform-specific images (amd64 & arm64) for actual runtime use
      #     # - 2 buildcache images (amd64 & arm64) used by buildx to speed up incremental builds
      #     # - Additional sha256 digests for content-addressable layers and manifests
      #     # These ensure proper support for multi-arch pulls and efficient rebuilds.
      #     min-versions-to-keep: 
      #     ignore-versions: '^buildcache-*'